server:
  port: 7186

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5440/TaskDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: none
  liquibase:
    enabled: false
    label-filter: "!stub-data"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: task
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.apache.kafka: OFF
    org.springframework.kafka: OFF

generate-service:
  url: "http://localhost:"

async-executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 5

mvc-executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 5

scheduler:
  delete-not-started-tasks: "*/3 * * * * *" # 3 seconds
  not-started-task-lifetime: 7