server:
  port: 7186

spring:
  application:
    name: task-service

  datasource:
    url: jdbc:postgresql://localhost:5440/TaskDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        #dialect: org.hibernate.dialect.PostgreSQLDialect :PostgreSQLDialect does not need to be specified explicitly using 'hibernate.dialect'
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
    #label-filter: "!stub-data"

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      bootstrap-servers: localhost:9092
      group-id: task
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
  tracing:
    sampling:
      probability: 1.0

generate-service:
  url: "http://GENERATE-BY-TEMPLATE/api/v1/generate"

async-executor:
  core-pool-size: 5 #this qnt of thread will be created when requests come, then request will go to queue
  max-pool-size: 10 # will be after queue capacity
  queue-capacity: 10 #after queue filling qnt of thread can be increased up to max pool size

mvc-executor:
  core-pool-size: 5
  max-pool-size: 10
  queue-capacity: 5

scheduler:
  delete-not-started-tasks: "@weekly"
  not-started-task-lifetime: 7