server:
  port: 7171

spring:
  application:
    name: authservice
  profiles:
    active: default

  config:
    import: "optional:configserver:http://localhost:8071"

access-token:
  public: "access-token-public.key"
  private: "access-token-private.key"
refresh-token:
  public: "refresh-token-public.key"
  private: "refresh-token-private.key"

logging:
  level:
    org.springframework.security: INFO