server:
  port: 7176

spring:
  application:
    name: generate-by-template
  cache:
    cache-names: template

  datasource:
    url: jdbc:postgresql://localhost:5434/TemplateDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml

  kafka:
    bootstrap-servers: localhost:9092
    passport-topic: passports
    consumer:
      bootstrap-servers: localhost:9092
      group-id: passport
      auto-offset-reset: earliest

minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: secretsecret
  bucket-name: templates

placeholder:
  upper-serial: NUMBERUP
  bottom-serial: NUMBERDOWN
  date: DATE
  date-format: "dd.MM.yyyy"

pdf-service:
  url: "http://localhost:3000/forms/libreoffice/convert"
  filename: "fileToConvert"

template:
  templates-per-page: 10

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

scheduling:
  delete-unsync: "@weekly"
  days-until-delete: 5

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
  tracing:
    sampling:
      probability: 1.0