version: "3.8"


services:

  postgres:
    container_name: postgres-pt
    image: "postgres:15.2"
    restart: unless-stopped
    env_file:
      - database.env
    ports:
      - "5433:5432"
    networks:
      - postgres
    volumes:
      - /var/docker-volumes/pg-pt-management-ps:/var/lib/postgresql/data/

  pdfConverter:
    container_name: pdfConverter
    image: gotenberg/gotenberg:7
    ports:
      - "3000:3000"

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"

  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    volumes:
      - /var/docker-volumes/minio-pt:/data
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data


networks:
  postgres:
    driver: bridge