server:
  port: 8083

spring:
  application:
    name: api-gateway
  profiles:
    active: default

  config:
    import: "optional:configserver:http://localhost:8071"

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8079/realms/pt-management/protocol/openid-connect/certs
          issuer-uri: http://localhost:8079/realms/pt-management

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: TRACE
    ru.veselov: TRACE