server:
  port: 7177

spring:
  application:
    name: managing
  cache:
    cache-names: customer, transducer
    caffeine:
      spec: initialCapacity=20,maximumSize=20,expireAfterAccess=3600s

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: none
  liquibase:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

serial:
  serialsPerPage: 100

customer:
  customersPerPage: 10

logging:
  level:
    ru.veselov.passportprocessing: debug

