server:
  port: 7175

placeholder:
  upper-serial: NUMBERUP
  bottom-serial: NUMBERDOWN
  date: DATE
  date-format: "dd.MM.yyyy"

pdf-service:
  url: "http://localhost:3000/forms/libreoffice/convert"
  filename: "fileToConvert"

template-storage:
  url: "http://localhost:7176/api/v1/template"

spring:
  application:
    name: passport
  cache:
    cache-names: templates
  main:
    allow-bean-definition-overriding: true

  kafka:
    bootstrap-servers: localhost:9092
    passport-topic: passports
    consumer:
      bootstrap-servers: localhost:9092
      group-id: passport
      auto-offset-reset: earliest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    ru.veselov.passportprocessing: debug
