server:
  port: 7176

spring:
  application:
    name: template-storage
  cache:
    cache-names: template

minio:
  url: http://localhost:9000
  accessKey: admin
  secretKey: secretsecret
  bucket-name: templates

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: false

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    ru.veselov.ru.veselov.miniotemplateservice: debug

