server:
  port: 7176

spring:
  application:
    name: generate-by-template
  profiles:
    active: default

  config:
    import: "optional:configserver:http://localhost:8071"

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yaml
