server:
  port: 8083

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: passport
          uri: lb://PASSPORT
          predicates:
            - Path=/api/v1/passport/**

        - id: template-storage
          uri: lb://TEMPLATE-STORAGE
          predicates:
            - Path=/api/v1/template/**

        - id: managing
          uri: lb://MANAGING
          predicates:
            - Path=/api/v1/customer/**,  /api/v1/transducer/**, /api/v1/serials/**, /api/v1/passport/**

        - id: discovery
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
  tracing:
    sampling:
      probability: 1.0