server:
  port: 7177

spring:
  application:
    name: managing
  cache:
    cache-names: customer, transducer
    caffeine:
      spec: initialCapacity=20,maximumSize=20,expireAfterAccess=3600s

  datasource:
    url: jdbc:postgresql://localhost:5433/PtManagementDB
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: false
        hbm2ddl:
          auto: validate
  liquibase:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health

  tracing:
    sampling:
      probability: 1.0

serial:
  serialsPerPage: 120

customer:
  customersPerPage: 10

transducer:
  transducersPerPage: 10

logging:
  level:
    ru.veselov.passportprocessing: debug

