server:
  port: 7175

placeholder:
  upper-serial: NUMBERUP
  bottom-serial: NUMBERDOWN
  date: DATE
  date-format: "dd.MM.yyyy"

pdf-service:
  url: "http://localhost:3000/forms/libreoffice/convert"
  filename: "fileToConvert"

template-storage:
  url: "http://TEMPLATE-STORAGE/api/v1/template"

spring:
  application:
    name: passport
  kafka:
    bootstrap-servers: localhost:9092
    passport-topic: passports

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health
  tracing:
    sampling:
      probability: 1.0